import { IconButton } from "@material-ui/core";
import {
  ArrowBack,
  CheckCircle,
  Delete,
  Email,
  Error,
  ExitToApp,
  LabelImportant,
  MoreVert,
  MoveToInbox,
  Print,
  UnfoldMore,
  WatchLater,
} from "@material-ui/icons";
import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import { useRouter } from "next/router";
import SendMail from "../components/SendMail";
import { selectSendMessageIsOpen } from "../features/mailSlice";
import { useSelector } from "react-redux";
import { db } from "../firebase";
import Login from "../components/Login";
import { getSession } from "next-auth/client";
import { useEffect } from "react";

function Mail({ email, session }) {
  const router = useRouter();
  const sendMessageIsOpen = useSelector(selectSendMessageIsOpen);

  useEffect(() => {
    if (!session) {
      router.push("/");
    }
  }, [router, session]);

  if (!session) return <Login />;

  return (
    <div className="mail">
      <Head>
        <title>Gmail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="mail__bodyContainer">
        <Sidebar />
        <div className="mail__body">
          <div className="mail__tools">
            <div className="mail__toolsLeft">
              <IconButton onClick={() => router.push("/")}>
                <ArrowBack />
              </IconButton>
              <IconButton>
                <MoveToInbox />
              </IconButton>
              <IconButton>
                <Error />
              </IconButton>
              <IconButton>
                <Delete />
              </IconButton>
              <IconButton>
                <Email />
              </IconButton>
              <IconButton>
                <WatchLater />
              </IconButton>
              <IconButton>
                <CheckCircle />
              </IconButton>
              <IconButton>
                <LabelImportant />
              </IconButton>
              <IconButton>
                <MoreVert />
              </IconButton>
            </div>
            <div className="mail__toolsRight">
              <IconButton>
                <UnfoldMore />
              </IconButton>
              <IconButton>
                <Print />
              </IconButton>
              <IconButton>
                <ExitToApp />
              </IconButton>
            </div>
          </div>
          <div className="mail__content">
            <div className="mail__contentHeader">
              <h2>{email?.subject}</h2>
              <LabelImportant className="mail__important" />
              <p>{email?.to}</p>
              <p className="mail__time">10pm</p>
            </div>
            <div className="mail__message">
              <p>{email?.message}</p>
            </div>
          </div>
        </div>
      </main>
      {sendMessageIsOpen && <SendMail />}
    </div>
  );
}

export default Mail;

export async function getServerSideProps(context) {
  // Get User
  const session = await getSession(context);

  const id = context.query.id;

  const email = await db.collection("emails").doc(id).get();

  const doc = {
    id: email.id,
    ...email.data(),
    timestamp: null,
  };

  return {
    props: { session, email: doc },
  };
}
